### ISSUE TITLE
What if i just want to have list of URL and some specific data like folder, uploaddate, views etc

### ISSUE THREAD

**Issue by RYG81** [GeorgeIpsum/dl-vimeo-account#4]
Hi,

Can it be used to just generate a list of all videos tile with their URL (private/public) and details like upload date, views, parent folder etc.

**Comment by GeorgeIpsum** [comment]
Hi @RYG81, sorry for the late reply here (haven't touched this repo in a while). If this is still relevant to you, you can pretty much stop the script past the `loadVideoData` function that's used internally to get all the data you need for each video. You'll need to expand the `fields` key to include all the data you're querying for (in the script I only query for video `uri` and `files` array)

**Comment by GeorgeIpsum** [comment]
Also, if you still wanted to record all of your data to `files.json`, you'd just stop the download process from happening by commenting out the execution of `downloadFiles()` in the `recordFiles` function

**Comment by RYG81** [comment]
thanks.
Though I am not good at coding yet I will try
